Traceback (most recent call last):
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.fft import fft

# Compute the Fourier transform
superposition_wave_fft = fft(superposition_wave)

# Frequency values for the Fourier transform
sampling_rate = 1 / (t[1] - t[0]) #1 sample per second
frequencies = np.fft.fftfreq(len(t), d=1/sampling_rate)

# Plot the Fourier transform
plt.figure(figsize=(8, 6))
plt.plot(frequencies, np.abs(superposition_wave_fft),'k',lw=2. label="Fourier Transform")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Amplitude")
plt.title("Fourier Transform of superposition wave")
------------------


[1;36m  Cell [1;32mIn[2], line 12[1;36m[0m
[1;33m    plt.plot(frequencies, np.abs(superposition_wave_fft),'k',lw=2. label="Fourier Transform")[0m
[1;37m                                                                ^[0m
[1;31mSyntaxError[0m[1;31m:[0m invalid syntax. Perhaps you forgot a comma?


