Traceback (most recent call last):
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

# Create time values
t = np.linspace(0, 2 * np.pi, 1000) #eight cycles

#define frequencies, phases, and amplitudes of three sine waves
frequencies=1./np.array([2*np.pi.,np.pi,2./np.pi])
phases=np.pi*np.array([1.,1./2,1./4])
amplitudes=np.array([1.,2.,4.])

# compute the wave signals
wave1 = amplitudes[0] * np.sin(2 * np.pi * frequencies[0] * t + phases[0])
wave2 = amplitudes[1] * np.sin(2 * np.pi * frequencies[1] * t + phases[1])
wave3 = amplitudes[2] * np.sin(2 * np.pi * frequencies[2] * t + phases[2])

#plot the wave signals
fig, ax = plt.subplots(2, 1, figsize=(8, 6), sharex=True)
ax[0].set_xlim(( 0, 2*np.pi))
ax[0].set_ylim((-4, 4))

line1, = ax[0].plot(t, wave1, lw = 2, label='wave 1')
line2, = ax[0].plot(t, wave2, lw = 2, label='wave 2')
line3, = ax[0].plot(t, wave3, lw = 2, label='wave 3')

line4, = ax[1].plot(t, wave1+wave2+wave3, lw = 2, label='Superposition')

ax[0].set_ylabel('f')
ax[0].set_title("Initial Condition")
ax[0].legend()
ax[1].legend()
ax[1].set_ylabel('f')
ax[1].set_xlabel('t')
------------------


[1;36m  Cell [1;32mIn[1], line 8[1;36m[0m
[1;33m    frequencies=1./np.array([2*np.pi.,np.pi,2./np.pi])[0m
[1;37m                                     ^[0m
[1;31mSyntaxError[0m[1;31m:[0m invalid syntax


