Traceback (most recent call last):
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.fft import fft, rfft
from scipy.fft import fftfreq, rfftfreq

# Compute the Fourier transform
superposition_wave_fft = fft(superposition_wave)
superposition_wave_real_fft=2*np.abs(rfft(superposition_wave))/N

# Calculate N/2 to normalize the FFT output
N = len(t)
normalize = N/2

# Frequency values for the Fourier transform
sampling_rate = 1 / (t[1] - t[0]) 
frequencies=fftfreq(N, d=1/sampling_rate) #real frequencies
#frequencies = np.fft.fftfreq(len(t), d=1/sampling_rate)

# Plot the Fourier transform
plt.figure(figsize=(8, 6))
plt.plot(frequencies, superposition_wave_real_fft,'k',lw=2, label="Fourier Transform")

plt.title('Spectrum')
plt.xlabel('Frequency[Hz]')
plt.ylabel('Amplitude')

plt.xlim([0,3*np.pi])
plt.xlabel("Frequency (Hz)")
plt.ylabel("Amplitude")
plt.title("Fourier Transform of superposition wave")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[2], line 6[0m
[0;32m      4[0m [38;5;66;03m# Compute the Fourier transform[39;00m
[0;32m      5[0m superposition_wave_fft [38;5;241m=[39m fft(superposition_wave)
[1;32m----> 6[0m superposition_wave_real_fft[38;5;241m=[39m[38;5;241m2[39m[38;5;241m*[39mnp[38;5;241m.[39mabs(rfft(superposition_wave))[38;5;241m/[39m[43mN[49m
[0;32m      8[0m [38;5;66;03m# Calculate N/2 to normalize the FFT output[39;00m
[0;32m      9[0m N [38;5;241m=[39m [38;5;28mlen[39m(t)

[1;31mNameError[0m: name 'N' is not defined

