Traceback (most recent call last):
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

t = np.arange(0,5,0.001)

square_wave = 1 - 2 * (t.astype(int) % 2)

N = 20 #number of frequencies to include
fsq = np.zeros_like(x) #fsw short for frequencies

for i in range(N): #loop through the 20 first sine waves
    n = 2*i + 1
    fsq += np.sin(n * np.pi *x) / n #adds the sine wave for n into the sum
fsq *= 5 / np.pi

fig, ax = plt.subplots()
ax.plot(x, square_wave,'k', lw=2)
ax.plot(x, fsq, 'r')
#ax.set_ylim(-1.2,1.2)


#ax.grid(b=True, c='k', lw=1, ls='--', which='major')
#ax.grid(b=True, c='0.4', lw=0.5, ls=':', which='minor')

plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[3], line 9[0m
[0;32m      6[0m square_wave [38;5;241m=[39m [38;5;241m1[39m [38;5;241m-[39m [38;5;241m2[39m [38;5;241m*[39m (t[38;5;241m.[39mastype([38;5;28mint[39m) [38;5;241m%[39m [38;5;241m2[39m)
[0;32m      8[0m N [38;5;241m=[39m [38;5;241m20[39m [38;5;66;03m#number of frequencies to include[39;00m
[1;32m----> 9[0m fsq [38;5;241m=[39m np[38;5;241m.[39mzeros_like([43mx[49m) [38;5;66;03m#fsw short for frequencies[39;00m
[0;32m     11[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m(N): [38;5;66;03m#loop through the 20 first sine waves[39;00m
[0;32m     12[0m     n [38;5;241m=[39m [38;5;241m2[39m[38;5;241m*[39mi [38;5;241m+[39m [38;5;241m1[39m

[1;31mNameError[0m: name 'x' is not defined

